//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 03:24:15 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://loadingjava.blogspot.in", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.blogspot.loadingjava;
